### PR TITLE
Fix comment inside 'nFrees'

### PR DESCRIPTION
**Pull request by rockbmb**
I'll take a general look at comments throughout the codebase to see if there's anything else that needs to be fixed as well. Seems a little wasteful to submit a PR just for one fix.

### CODE REVIEW

**Comment by rockbmb** [comment]
This reminds me, this project has no `README.md`. I'll write something to start, but not as a part of this PR.

**Comment by Bodigrim** [comment]
Writing a decent README is an amazing idea!

**Comment by rockbmb** [comment]
Couldn't find anything pressing among the things I wrote before. This can be merged now, if I spot anything else I'll submit a new PR.

Meanwhile, I'll start thiking about that README. Writing rockbmb/gamma2/README.md gave me a good starting idea.

**Comment by Bodigrim** [comment]
Thanks!

**Pull request merged**
