### PR TITLE
Enumerating the Rationals

### PR DESCRIPTION
**Pull request by fizruk**
This PR is based on a functional pearl [_Enumerating the Rationals_](http://www.cs.ox.ac.uk/jeremy.gibbons/publications/rationals.pdf).

This is just basic implementation for enumerating the rationals (and also pairs of coprime numbers).
I can also add Stern-Brocot and Calkin-Wilf trees as well as generating rationals as continued fractions.

### CODE REVIEW

**Comment by cartazio** [comment]
Cool!  I'll take a look sometime next week.  Next few days are kinda crazy
for me

**Comment by Bodigrim** [comment]
Wow, this functional pearl is great. 
@fizruk could you please benchmark your `positiveCoprimes` vs. naive `concat [[(x,y), (y,x)] | x<-[1..], y<-[1..x-1], coprime x y]`? Are there any other applications of Calkin-Wilf tree to the number theory? 

It would be nice to have continuous fractions and related stuff in `arithmoi` accompanied with their applications in diophantine equations (e. g., generalised Pell equation  http://people.ucalgary.ca/~ramollin/ACFappraochto.pdf).

**Comment by rockbmb** [comment]
Hello;

@Bodigrim do you think this issue is still relevant? If so, @fizruk do you mind if I work on it?

**Comment by Bodigrim** [comment]
Unfortunately, closing as being currently out-of-scope. Thanks for contribution, any way.

**Pull request closed without merging**
