### PR TITLE
Support integer-gmp-1.0.0

### LINKED ISSUE #1: Add support for `integer-gmp-1.0.0`
see also #3

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #1

### CODE REVIEW

**Comment by cartazio** [comment]
@shlevy  i think you actually want to use < =709 as your bound on the GHC version.

**Comment by shlevy** [comment]
@cartazio amended.

**Comment by cartazio** [comment]
@shlevy  i'm going to merge this into master this evening, but i'd appreciate some help adding test coverage of the code it touched before doing the next hackage release.

**Comment by cartazio** [comment]
https://travis-ci.org/cartazio/arithmoi/builds/65831176 is the branch that has your commits thati'm running through basic CI now

**Comment by cartazio** [comment]
@hvr any clue what those build failures mean? should i just rerun the build?

**Comment by cartazio** [comment]
eg 
``
[4 of 9] Compiling Data.Binary.Builder ( src/Data/Binary/Builder.hs, dist/build/Data/Binary/Builder.o )
Implicit import declaration:
    base:Prelude can't be safely imported! The package (base) the module resides in isn't trusted.
Failed to install binary-0.7.5.0
``
in 
https://travis-ci.org/cartazio/arithmoi/jobs/65831182#L671

**Comment by hvr** [comment]
@cartazio GHC 7.2 is a lost cause IMHO; feel free to unsupport it by excluding `base==4.4.*`

**Comment by shlevy** [comment]
@cartazio I'd be happy to write a test given a test framework

**Comment by cartazio** [comment]
sh

**Comment by cartazio** [comment]
@shlevy  ok, after I adjust to get travis green on the branch, i'll merge it into master

**Comment by cartazio** [comment]
@shlevy  fire away!

**Pull request merged**
