### PR TITLE
Modular arithmetic

### PR DESCRIPTION
**Pull request by Bodigrim**
This branch has started as an attempt to speed up the implementation of factorization on elliptic curve (#21, #23). The algorithm requires many reductions modulo some big integer. Soon enough I realised that writing them manually is very tedious. E. g., one can write

    a * b * c `mod` m,

but if numbers are big enough, it is preferable to perform reductions after each multiplication. So we write

    a * b `mod` m * c `mod` m.

But if `a`, `b` and `c` were not reduced beforehand and are larger than `m`, it is even better to write

    (a `mod` m) * (b `mod` m) `mod` m * (c `mod` m) `mod` m.

When the code is so submerged under the weight of backticks and brackets, only the brave heart would dare to refactor it. The aim of the proposed branch is to make things easier in two ways:

* Reductions are performed behind the scenes in `Num` instance.
* Type system prevents adding numbers, reducted modulo different numbers. This is a common source of errors.

Despite the initial target was factorization algorithm, I have postponed it to a separate branch: [draft](https://github.com/Bodigrim/arithmoi/tree/montgomery2).

---

The solution is to define a type, which keeps its modulo as a type-level natural:

```haskell
newtype Mod (m :: Nat) = Mod Integer
  deriving (Eq, Ord)
```

The `Num` instance is straightforward:

```haskell
instance KnownNat m => Num (Mod m) where
  mx@(Mod x) * Mod y = Mod $ x * y `mod` natVal mx
  mx@(Mod x) + Mod y = Mod $ if xy >= m then xy - m else xy
    where
      xy = x + y
      m = natVal mx
  negate mx@(Mod x) = Mod $ if x == 0 then 0 else natVal mx - x
  abs = id
  signum = const $ Mod 1
  fromInteger x = mx
    where
      mx = Mod $ fromInteger $ x `mod` natVal mx
```

We always keep the value in normalized form between `0` and `m-1`, because it allows to use derived `Eq` and `Ord` instances.

There are also `invertMod :: Mod m -> Maybe (Mod m)` and `powMod :: Mod m -> a -> Mod m` functions, expressed in terms of GMP calls, which is faster than previous manual implementations.

---

The next abstraction is GADT `SomeMod`. Its design was partially inspired by [PARI/GP](https://pari.math.u-bordeaux.fr/doc.html). (In fact, many my design decisions are inspired by PARI/GP, which is as wonderful for number-theory, as it is lacking type discipline and containers.)

The first constructor is a standard approach, hiding type parameter (as in `KnownNat/SomeNat`, `KnownSymbol/SomeSymbol`).

```haskell
data SomeMod where
  SomeMod :: KnownNat m => Mod m -> SomeMod
```

Now we define `modulo` function to construct `Mod`, when modulo is not known at compile time:

```haskell
modulo :: Integer -> Natural -> SomeMod
modulo n m = case someNatVal (toInteger m) of
  Nothing                       -> error "modulo: negative modulo"
  Just (SomeNat (_ :: Proxy t)) -> SomeMod (fromInteger n :: Mod t)
```

It is possible (and actually quite useful) to define arithmetic operations on `SomeMod` by rule

```haskell
(Mod x1 :: Mod m1) `f` (Mod x2 :: Mod m2) = Mod (x1 `f` x2) :: Mod (m1 `gcd` m2).
```

E. g.,

```haskell
2 `modulo` 10 + 4 `modulo` 15 = 1 `modulo` 5
```

But we still cannot define `Num` instance, because it is impossible to implement righteous `fromInteger` function: it takes only one argument, but to construct `SomeMod` both value and modulo are required. This is resolved by adding another constructor `InfMod` to `SomeMod` GADT and some plumbing.

---

Benchmarks show that `isStrongFermatPP` became 2x-6x faster (due to use of GMP built-in for modular power). The performance of `factorise` on large numbers became worse, but its current implementation is slow as hell any way. Its performance is the subject of [montgomery2](https://github.com/Bodigrim/arithmoi/tree/montgomery2) branch.

---

At the final stage of the work on this branch I have found [modular-arithmetic](https://github.com/TikhonJelvis/modular-arithmetic) package, which implements a similar approach to modular arithmetic. (All coincidences of names are accidental.) The main advantages of the proposed PR are:

* Usage of fast GMP calls to invert modular values.
* Implementation of arithmetic on `SomeMod`.
* `Mod` is an instance of `Fractional` and is not an instance of `Integral` (see the issue TikhonJelvis/modular-arithmetic#8 by @CarlEdman)
* Last, but not least: there are tests!

### CODE REVIEW

**Comment by cartazio** [comment]
Very cool.

This sounds like it merits a nice design and code review. Please holler my
way if I'm being Too slow about it.

Off the cuff I think you actually want to look at the reflection package by
ed. It allows you to have the shared modulus be selected at runtime but
still be type indexed.

Which might let you drop / cleanup the design I think ?

**Comment by cartazio** [comment]
yeah .. looks like Reflection would be handy here

something like 

`Reifies Nat s => Num (Mod s)` perhaps?
or something like that

**Comment by Bodigrim** [comment]
`reflection` is very handy in more complex cases, when required instances cannot be simply parametrised by type. Here choice of `Num` and `Fractional` instances is done entirely on basis of type-level `Nat`, and it is a built-in kind with handy helpers from `GHC.TypeLits`.

**Comment by cartazio** [comment]
hrmmm... maybe? 
please message/email me a reminder to have a go at doing a fork that ports this PR to that style this weekend or next week so we can compare them hand to hand or i at least try and then give up and agree :)

**Comment by cartazio** [comment]
I'll have a go  this evening / tomorrow at this :)

**Comment by cartazio** [comment]
It's on the top of my todo queue this week :)

**Comment by Bodigrim** [comment]
If there will be no suggestions, I'd like to merge the branch by the end of the month.

**Comment by cartazio** [comment]
Derp yeah. Sorry :)
I'm suspecting you're right.

**Comment by cartazio** [comment]
sounds good to me, i'll still give it a review / go over once some work deadlines clear up :)

**Pull request merged**
