### PR TITLE
Add tests for integer-gmp-1 changes

### PR DESCRIPTION
**Pull request by shlevy**
refs #3

### CODE REVIEW

**Comment by shlevy** [comment]
@cartazio I'll ping you when this is done.

**Comment by cartazio** [comment]
Great! Many thanks.  I'll be more than happy to code review it once you
indicate it's ready.

Arithmoi definitely needs some testing and benchmarking of public Apis if
we're to evolve it in a meaningful way going forward!

**Comment by shlevy** [comment]
@cartazio ready.

**Comment by cartazio** [comment]
thanks
ill cut a release now

**Comment by cartazio** [comment]
(well, after travis shows all green)

**Pull request merged**
