### PR TITLE
Smooth Numbers module

### PR DESCRIPTION
**Pull request by grandpascorpion**
Functions for generating smooth numbers in various ways.

### CODE REVIEW

**Comment by Bodigrim** [comment]
Thanks for contributing! Your efforts are much appreciated.

There is a common pattern, which seems applicable here. Namely, to separate validation from actual computations, using a newtype with unexported constructor. 

I suggest to introduce a newtype and following validating routines: 

```haskell
newtype SmoothBasis a = SmoothBasis [a]

fromSet :: S.Set a -> Maybe (SmoothBasis a)
fromSet s = if validU l then Just (SmoothBasis l) else Nothing where l = S.elems s

fromList :: [a] -> Maybe (SmoothBasis a)
fromList l' = if validU l then Just (SmoothBasis l) else Nothing where l = nub $ sort l'
```

Further, we define **total** functions:

```haskell
smoothOver          :: Integral a => SmoothBasis a -> [a]
smoothOverInRange   :: Integral a => SmoothBasis a -> a -> a -> [a]
smoothOverInRangeBF :: Integral a => SmoothBasis a -> a -> a -> [a]
```

There are several advantages:

1. User can easily catch `Nothing`, if his input was invalid. 
   Throwing `error` from internals of the library is much more cumbersome 
   to handle: basically, user must do computations in `IO` monad.

2. User can validate a smooth basis once and use it multiple times. 
   Validation may be quite expensive here.

3. There is no need to have `Set`- and `List`-flavours of each function.

**Comment by grandpascorpion** [comment]
Thanks for the insight, Andrew.  Will try to turn this around shortly.

Best, Fred

**Comment by Bodigrim** [comment]
Awesome! One last suggestion: what UB in `fromSmoothUB` stands for? Could it possibly be renamed to `fromPrimesUpTo` or something similar?

**Comment by grandpascorpion** [comment]
UB means Upper Bound

**Comment by grandpascorpion** [comment]
Cool, thanks for your patience.

By the way, I have released my massive number library:
https://hackage.haskell.org/package/canon

Still early, so there may be some bugs.  The next release will have robust
support of hyperoperations (https://en.wikipedia.org/wiki/Hyperoperation)
so I can finally define Graham's number without blowing up the universe :)

Best, Fred

**Comment by Bodigrim** [comment]
Cool! It would be nice to have some examples of usage directly in haddock documentation.

**Comment by grandpascorpion** [comment]
Great point.  I will try to turn that around today.

**Comment by grandpascorpion** [comment]
Done

**Pull request merged**
