### PR TITLE
Release 0.4.3

### PR DESCRIPTION
**Pull request by Bodigrim**
As requested in #40

### CODE REVIEW

**Comment by cartazio** [comment]
Sounds good to me, I trust your judgement on this stuff :)

**Comment by cartazio** [comment]
Hrm, it looks like we could get the tests green on ghc master if we did some cpp and ghc options shenanigans.  I think suppressing the simplifiable constraint warning may or may not be useful.  I'm not sure. Or maybe it could be made simpler?

**Comment by Bodigrim** [comment]
AFAIR I had tried to use `MonoLocalBinds` as the warning suggests, but it did not help. And IARC simplifying the instance also triggered another troubles. I do not have GHC HEAD at my workstation, so it is cumbersome to test. 

I am not sure what exactly has changed between GHC 8.0 and GHC HEAD, and whether the warning is genuine or only a quirk of unstable version. That means that adding some cpp magic looks to me a bit premature, but if you know what exactly is going on and how to fix it (more or less :) cleanly - I definitely do not mind.

Otherwise, this is a warning, not an error, so it would not prevent `arithmoi` to build in future. And I hope that we will make another release or two before GHC 8.2 lands :)

**Comment by cartazio** [comment]
... This has to do with a different language issue than that.  But yeah not
a blocker.

It has to do with the redundant constraint warnings and some changes
related to that I think.  Though I thought some of that was going to be
removed from wall in 8.2 so etc etc etc

**Pull request merged**
